language: perl
perl:
  - 5.22
  - "5.20"
  - 5.18

before_install:
   - sudo apt-get install ditaa
   - git clone git://github.com/haarg/perl-travis-helper
   - source perl-travis-helper/init
   - build-perl
   - perl -V

install:
  - cpanm -nq --installdeps .
  - cpanm -nq Devel::Cover::Report::Coveralls
script:
   - PERL5OPT=-MDevel::Cover=-coverage,statement,branch,condition,path,subroutine prove -lrsv t
   - cover
after_success:
  - cover -report coveralls
